# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kolan/stm/STM32F1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kolan/stm/STM32F1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kolan/stm/STM32F1/CMakeFiles /home/kolan/stm/STM32F1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kolan/stm/STM32F1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named flash

# Build rule for target.
flash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flash
.PHONY : flash

# fast build rule for target.
flash/fast:
	$(MAKE) -f CMakeFiles/flash.dir/build.make CMakeFiles/flash.dir/build
.PHONY : flash/fast

#=============================================================================
# Target rules for targets named generate_bin

# Build rule for target.
generate_bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generate_bin
.PHONY : generate_bin

# fast build rule for target.
generate_bin/fast:
	$(MAKE) -f CMakeFiles/generate_bin.dir/build.make CMakeFiles/generate_bin.dir/build
.PHONY : generate_bin/fast

#=============================================================================
# Target rules for targets named generate_hex

# Build rule for target.
generate_hex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generate_hex
.PHONY : generate_hex

# fast build rule for target.
generate_hex/fast:
	$(MAKE) -f CMakeFiles/generate_hex.dir/build.make CMakeFiles/generate_hex.dir/build
.PHONY : generate_hex/fast

#=============================================================================
# Target rules for targets named stm32learn.elf

# Build rule for target.
stm32learn.elf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stm32learn.elf
.PHONY : stm32learn.elf

# fast build rule for target.
stm32learn.elf/fast:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/build
.PHONY : stm32learn.elf/fast

Boot/startup_stm32f103xb.o: Boot/startup_stm32f103xb.s.o
.PHONY : Boot/startup_stm32f103xb.o

# target to build an object file
Boot/startup_stm32f103xb.s.o:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/Boot/startup_stm32f103xb.s.o
.PHONY : Boot/startup_stm32f103xb.s.o

Boot/startup_stm32f103xb.i: Boot/startup_stm32f103xb.s.i
.PHONY : Boot/startup_stm32f103xb.i

# target to preprocess a source file
Boot/startup_stm32f103xb.s.i:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/Boot/startup_stm32f103xb.s.i
.PHONY : Boot/startup_stm32f103xb.s.i

Boot/startup_stm32f103xb.s: Boot/startup_stm32f103xb.s.s
.PHONY : Boot/startup_stm32f103xb.s

# target to generate assembly for a file
Boot/startup_stm32f103xb.s.s:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/Boot/startup_stm32f103xb.s.s
.PHONY : Boot/startup_stm32f103xb.s.s

Boot/system_stm32f1xx.o: Boot/system_stm32f1xx.c.o
.PHONY : Boot/system_stm32f1xx.o

# target to build an object file
Boot/system_stm32f1xx.c.o:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/Boot/system_stm32f1xx.c.o
.PHONY : Boot/system_stm32f1xx.c.o

Boot/system_stm32f1xx.i: Boot/system_stm32f1xx.c.i
.PHONY : Boot/system_stm32f1xx.i

# target to preprocess a source file
Boot/system_stm32f1xx.c.i:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/Boot/system_stm32f1xx.c.i
.PHONY : Boot/system_stm32f1xx.c.i

Boot/system_stm32f1xx.s: Boot/system_stm32f1xx.c.s
.PHONY : Boot/system_stm32f1xx.s

# target to generate assembly for a file
Boot/system_stm32f1xx.c.s:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/Boot/system_stm32f1xx.c.s
.PHONY : Boot/system_stm32f1xx.c.s

Lib/printf.o: Lib/printf.c.o
.PHONY : Lib/printf.o

# target to build an object file
Lib/printf.c.o:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/Lib/printf.c.o
.PHONY : Lib/printf.c.o

Lib/printf.i: Lib/printf.c.i
.PHONY : Lib/printf.i

# target to preprocess a source file
Lib/printf.c.i:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/Lib/printf.c.i
.PHONY : Lib/printf.c.i

Lib/printf.s: Lib/printf.c.s
.PHONY : Lib/printf.s

# target to generate assembly for a file
Lib/printf.c.s:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/Lib/printf.c.s
.PHONY : Lib/printf.c.s

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.o: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c.o
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.o

# target to build an object file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c.o:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c.o
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c.o

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.i: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c.i
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.i

# target to preprocess a source file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c.i:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c.i
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c.i

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.s: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c.s
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.s

# target to generate assembly for a file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c.s:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c.s
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c.s

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.o: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c.o
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.o

# target to build an object file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c.o:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c.o
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c.o

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.i: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c.i
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.i

# target to preprocess a source file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c.i:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c.i
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c.i

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.s: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c.s
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.s

# target to generate assembly for a file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c.s:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c.s
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c.s

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.o: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c.o
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.o

# target to build an object file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c.o:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c.o
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c.o

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.i: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c.i
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.i

# target to preprocess a source file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c.i:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c.i
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c.i

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.s: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c.s
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.s

# target to generate assembly for a file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c.s:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c.s
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c.s

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.o: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c.o
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.o

# target to build an object file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c.o:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c.o
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c.o

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.i: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c.i
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.i

# target to preprocess a source file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c.i:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c.i
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c.i

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.s: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c.s
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.s

# target to generate assembly for a file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c.s:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c.s
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c.s

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.o: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c.o
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.o

# target to build an object file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c.o:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c.o
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c.o

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.i: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c.i
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.i

# target to preprocess a source file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c.i:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c.i
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c.i

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.s: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c.s
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.s

# target to generate assembly for a file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c.s:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c.s
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c.s

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.o: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c.o
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.o

# target to build an object file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c.o:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c.o
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c.o

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.i: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c.i
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.i

# target to preprocess a source file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c.i:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c.i
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c.i

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.s: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c.s
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.s

# target to generate assembly for a file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c.s:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c.s
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c.s

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.o: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c.o
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.o

# target to build an object file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c.o:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c.o
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c.o

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.i: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c.i
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.i

# target to preprocess a source file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c.i:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c.i
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c.i

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.s: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c.s
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.s

# target to generate assembly for a file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c.s:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c.s
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c.s

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.o: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c.o
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.o

# target to build an object file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c.o:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c.o
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c.o

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.i: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c.i
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.i

# target to preprocess a source file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c.i:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c.i
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c.i

home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.s: home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c.s
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.s

# target to generate assembly for a file
home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c.s:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c.s
.PHONY : home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/main.c.s
.PHONY : main.c.s

stm32f1xx_hal_msp.o: stm32f1xx_hal_msp.c.o
.PHONY : stm32f1xx_hal_msp.o

# target to build an object file
stm32f1xx_hal_msp.c.o:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/stm32f1xx_hal_msp.c.o
.PHONY : stm32f1xx_hal_msp.c.o

stm32f1xx_hal_msp.i: stm32f1xx_hal_msp.c.i
.PHONY : stm32f1xx_hal_msp.i

# target to preprocess a source file
stm32f1xx_hal_msp.c.i:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/stm32f1xx_hal_msp.c.i
.PHONY : stm32f1xx_hal_msp.c.i

stm32f1xx_hal_msp.s: stm32f1xx_hal_msp.c.s
.PHONY : stm32f1xx_hal_msp.s

# target to generate assembly for a file
stm32f1xx_hal_msp.c.s:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/stm32f1xx_hal_msp.c.s
.PHONY : stm32f1xx_hal_msp.c.s

stm32f1xx_it.o: stm32f1xx_it.c.o
.PHONY : stm32f1xx_it.o

# target to build an object file
stm32f1xx_it.c.o:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/stm32f1xx_it.c.o
.PHONY : stm32f1xx_it.c.o

stm32f1xx_it.i: stm32f1xx_it.c.i
.PHONY : stm32f1xx_it.i

# target to preprocess a source file
stm32f1xx_it.c.i:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/stm32f1xx_it.c.i
.PHONY : stm32f1xx_it.c.i

stm32f1xx_it.s: stm32f1xx_it.c.s
.PHONY : stm32f1xx_it.s

# target to generate assembly for a file
stm32f1xx_it.c.s:
	$(MAKE) -f CMakeFiles/stm32learn.elf.dir/build.make CMakeFiles/stm32learn.elf.dir/stm32f1xx_it.c.s
.PHONY : stm32f1xx_it.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... generate_bin"
	@echo "... stm32learn.elf"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... flash"
	@echo "... generate_hex"
	@echo "... Boot/startup_stm32f103xb.o"
	@echo "... Boot/startup_stm32f103xb.i"
	@echo "... Boot/startup_stm32f103xb.s"
	@echo "... Boot/system_stm32f1xx.o"
	@echo "... Boot/system_stm32f1xx.i"
	@echo "... Boot/system_stm32f1xx.s"
	@echo "... Lib/printf.o"
	@echo "... Lib/printf.i"
	@echo "... Lib/printf.s"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.o"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.i"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.s"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.o"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.i"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.s"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.o"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.i"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.s"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.o"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.i"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.s"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.o"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.i"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.s"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.o"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.i"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.s"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.o"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.i"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.s"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.o"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.i"
	@echo "... home/kolan/STM32Cube/Repository/STM32Cube_FW_F1_V1.3.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... stm32f1xx_hal_msp.o"
	@echo "... stm32f1xx_hal_msp.i"
	@echo "... stm32f1xx_hal_msp.s"
	@echo "... stm32f1xx_it.o"
	@echo "... stm32f1xx_it.i"
	@echo "... stm32f1xx_it.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

